#!/usr/bin/env bash
set -euo pipefail

# If you want, change these default paths

# STATE_PATH="$HOME/.local/state/apkgs"
# BIN_PATH="$HOME/.local/bin/apkgs"

# Add custom repositories 

# USE_PARU="1"
# USE_YAY="1"
# USE_FLATPAK="1"

USE_PARU="${USE_PARU:-0}"
USE_YAY="${USE_YAY:-0}"
USE_FLATPAK="${USE_FLATPAK:-0}"

STATE_PATH=${STATE_PATH:-"$HOME/.local/state/apkgs"}
BIN_PATH=${BIN_PATH:-"$HOME/.local/bin"}
CONFIG_PATH="$HOME/.config/apkgs"

mkdir -pv "$STATE_PATH" "$BIN_PATH" "$CONFIG_PATH"
touch "$STATE_PATH/pacman" "$STATE_PATH/paru" "$STATE_PATH/flatpak" "$STATE_PATH/yay"

if [[ "$USE_PARU" == "1" && "$USE_YAY" == "1" ]];then
	echo "You enabled both paru and yay, reconsider your life choises"
	echo "Exiting ..."
	exit 1
fi

# Move binnary
if [[ ! -f "apkgs" ]]; then
	echo "apkgs binary not found"
	echo "Exiting ..."
	exit 1
fi

mv -v "apkgs" "$BIN_PATH/apkgs"

# Save user prefs
cat > "$CONFIG_PATH/apkgs.conf" <<EOF
STATE_PATH="$STATE_PATH" 
USE_PARU="$USE_PARU"
USE_YAY="$USE_YAY"
USE_FLATPAK="$USE_FLATPAK" 
EOF

echo "Installation successfull"

